# Generated by Django 5.2.1 on 2025-05-20 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coustom_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostels',
            name='total_floors',
            field=models.IntegerField(),
        ),
    ]
