# Generated by Django 5.2.1 on 2025-06-08 05:41

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings
import django.utils.timezone

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coustom_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomAssignment',
            fields=[
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='room_assignment', serialize=False, to='coustom_admin.bookingrequest')),
                ('check_in_date', models.DateField(help_text='Actual check-in date')),
                ('check_out_date', models.DateField(blank=True, help_text='Check-out date. Leave empty if currently occupied.', null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Any additional notes about this assignment.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this assignment is currently active.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(help_text='Admin who made this assignment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_rooms', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(help_text='The assigned room for this booking.', on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='coustom_admin.rooms')),
            ],
            options={
                'ordering': ['-assigned_at'],
                'verbose_name': 'Room Assignment',
                'verbose_name_plural': 'Room Assignments',
            },
        ),
    ]
