# Generated by Django 5.2.1 on 2025-06-12 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coustom_admin', '0002_alter_hostelwardens_warden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelwardens',
            name='warden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coustom_admin.wardens'),
        ),
    ]
