# Generated by Django 5.2.1 on 2025-05-20 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coustom_admin', '0002_alter_hostels_total_floors'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostels',
            name='gender',
            field=models.CharField(default='Boys'),
        ),
    ]
