# Generated by Django 4.2.11 on 2024-05-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coustom_admin', '0003_alter_hostelwardens_warden'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bookingrequest',
            constraint=models.UniqueConstraint(
                fields=['student', 'status'],
                condition=models.Q(('status__in', ['Pending', 'Approved'])),
                name='unique_active_booking_per_student'
            ),
        ),
    ]