# Generated by Django 5.2.1 on 2025-05-21 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coustom_admin', '0004_wardens'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostels',
            name='warden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_hostel', to='coustom_admin.wardens'),
        ),
        migrations.AlterField(
            model_name='wardens',
            name='hostel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wardens', to='coustom_admin.hostels'),
        ),
    ]
