# Generated by Django 5.2.1 on 2025-06-15 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coustom_admin', '0004_add_unique_constraint_to_bookingrequest'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bookingrequest',
            name='unique_active_booking_per_student',
        ),
    ]
