# Generated by Django 5.2.1 on 2025-05-21 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coustom_admin', '0005_hostels_warden_alter_wardens_hostel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostels',
            name='warden',
        ),
        migrations.RemoveField(
            model_name='wardens',
            name='hostel',
        ),
        migrations.CreateModel(
            name='HostelWardens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coustom_admin.hostels')),
                ('warden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coustom_admin.wardens')),
            ],
        ),
    ]
