# Generated by Django 5.2.1 on 2025-06-01 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coustom_admin', '0007_alter_hostels_description_alter_hostels_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingrequest',
            name='room_type',
            field=models.CharField(choices=[('Single', 'Single'), ('Double', 'Double'), ('Shared', 'Shared')], default='Single'),
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=50, unique=True)),
                ('room_type', models.CharField(choices=[('Single', 'Single'), ('Double', 'Double'), ('Shared', 'Shared')], max_length=20)),
                ('capacity', models.IntegerField()),
                ('current_occupants', models.IntegerField(default=0)),
                ('rent', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Occupied', 'Occupied')], default='Available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hostel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coustom_admin.hostels')),
            ],
        ),
    ]
