# Generated by Django 5.2.1 on 2025-06-01 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coustom_admin', '0008_alter_bookingrequest_room_type_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='floor_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='rent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RoomTypeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('Single', 'Single'), ('Double', 'Double'), ('Shared', 'Shared')], max_length=20)),
                ('per_head_rent', models.IntegerField()),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coustom_admin.hostels')),
            ],
            options={
                'unique_together': {('hostel', 'room_type')},
            },
        ),
    ]
