# Generated by Django 5.2.1 on 2025-06-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coustom_admin', '0008_student_area_student_city_student_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='guardian_cnic',
            field=models.CharField(blank=True, help_text='Enter CNIC without dashes (e.g., 1234567890123)', max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_relation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
