# Generated by Django 5.2.1 on 2025-06-23 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coustom_admin', '0009_student_guardian_cnic_student_guardian_relation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messincharge',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='messincharge',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='messincharge',
            name='cnic',
            field=models.CharField(default='N/A', help_text='Enter CNIC without dashes (e.g., 1234567890123)', max_length=13, unique=True),
        ),
        migrations.AddField(
            model_name='messincharge',
            name='district',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='messincharge',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
