# Generated by Django (assumed version) on 2025-06-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coustom_admin', '0012_studentmonthlyfee'),
    ]

    operations = [
        migrations.AddField(
            model_name='Hostels',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10),
        ),
    ]
