# Generated by Django 5.2.1 on 2025-06-21 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coustom_admin', '0009_student_guardian_cnic_student_guardian_relation_and_more'),
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityguard',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='securityguard',
            name='hostel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='security_guards', to='coustom_admin.hostels'),
        ),
        migrations.AddField(
            model_name='securityguard',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='securityguard',
            name='shift',
            field=models.CharField(blank=True, choices=[('Morning', 'Morning'), ('Evening', 'Evening'), ('Night', 'Night')], max_length=20, null=True),
        ),
    ]
