# Generated by Django 5.2.1 on 2025-06-21 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coustom_admin', '0009_student_guardian_cnic_student_guardian_relation_and_more'),
        ('security', '0002_securityguard_gender_securityguard_hostel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'In'), ('OUT', 'Out')], max_length=3)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('hostel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='coustom_admin.hostels')),
                ('security_guard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorded_movements', to='security.securityguard')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='coustom_admin.student')),
            ],
            options={
                'verbose_name': 'Student Movement',
                'verbose_name_plural': 'Student Movements',
                'ordering': ['-timestamp'],
            },
        ),
    ]
