# Generated by Django 5.2.1 on 2025-06-21 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coustom_admin', '0009_student_guardian_cnic_student_guardian_relation_and_more'),
        ('security', '0003_studentmovement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cnic', models.CharField(help_text='Enter CNIC without dashes (e.g., 1234567890123)', max_length=15, unique=True)),
                ('contact_number', models.CharField(max_length=15)),
                ('relationship', models.CharField(blank=True, help_text='Relationship to the student (e.g., Parent, Guardian)', max_length=50, null=True)),
                ('purpose', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('hostel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitors', to='coustom_admin.hostels')),
                ('security_guard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_visitors', to='security.securityguard')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitors', to='coustom_admin.student')),
            ],
            options={
                'verbose_name': 'Visitor',
                'verbose_name_plural': 'Visitors',
                'ordering': ['-timestamp'],
            },
        ),
    ]
