# Generated by Django 5.2.1 on 2025-06-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0004_visitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='to_visted',
            field=models.CharField(choices=[('warden', 'Warden'), ('security_guard', 'Security Guard'), ('student', 'Student'), ('other', 'Other')], default='warden', help_text='Who the visitor is visiting', max_length=100),
        ),
    ]
