# Generated by Django 5.2.1 on 2025-06-21 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0005_visitor_to_visted'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', help_text='Status of the visit', max_length=20),
        ),
    ]
