# Generated by Django 5.2.1 on 2025-06-22 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coustom_admin', '0009_student_guardian_cnic_student_guardian_relation_and_more'),
        ('security', '0007_alter_visitor_cnic'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('fire', 'Fire Emergency'), ('medical', 'Medical Emergency'), ('security_breach', 'Security Breach'), ('natural_disaster', 'Natural Disaster'), ('other', 'Other Emergency')], max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('notify_all', models.BooleanField(default=True)),
                ('hostel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_alerts', to='coustom_admin.hostels')),
                ('security_guard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_alerts', to='security.securityguard')),
            ],
            options={
                'verbose_name': 'Emergency Alert',
                'verbose_name_plural': 'Emergency Alerts',
                'ordering': ['-timestamp'],
            },
        ),
    ]
