# Generated by Django 5.2.1 on 2025-06-30 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0008_emergencyalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityguard',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10),
        ),
    ]
