# Generated by Django 5.2.1 on 2025-06-16 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='submitted_to',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Warden', 'Warden')], default='Admin', max_length=10),
        ),
    ]
