# Generated by Django 5.2.1 on 2025-06-18 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coustom_admin', '0006_messincharge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessMenu',
            fields=[
                ('menu_id', models.AutoField(primary_key=True, serialize=False)),
                ('day_of_week', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10)),
                ('meal_type', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], max_length=10)),
                ('items', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_menus', to=settings.AUTH_USER_MODEL)),
                ('hostel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mess_menus', to='coustom_admin.hostels')),
            ],
            options={
                'verbose_name': 'Mess Menu',
                'verbose_name_plural': 'Mess Menus',
                'unique_together': {('hostel_id', 'day_of_week', 'meal_type')},
            },
        ),
    ]
