# Generated by Django 5.2.1 on 2025-06-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coustom_admin', '0006_messincharge'),
        ('messincharge', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='messmenu',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='messmenu',
            name='week_start_date',
            field=models.DateField(blank=True, help_text='Start date of the week for this menu', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='messmenu',
            unique_together={('hostel_id', 'day_of_week', 'meal_type', 'week_start_date')},
        ),
    ]
