# Generated by Django 5.2.1 on 2025-06-19 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coustom_admin', '0006_messincharge'),
        ('messincharge', '0002_alter_messmenu_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('expense_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(help_text='Description of the expense (e.g., Food Supplies, Utilities)', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount spent', max_digits=10)),
                ('date_incurred', models.DateField(help_text='Date when the expense was incurred')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receipt', models.FileField(blank=True, help_text='Upload receipt or proof of expense', null=True, upload_to='expenses_receipts/')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expenses', to=settings.AUTH_USER_MODEL)),
                ('hostel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mess_expenses', to='coustom_admin.hostels')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
            },
        ),
    ]
