# Generated by Django 5.2.1 on 2025-06-25 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coustom_admin', '0010_messincharge_area_messincharge_city_and_more'),
        ('messincharge', '0004_messstudent'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessAttendance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(help_text='Date of attendance')),
                ('breakfast', models.BooleanField(default=False, help_text='Attendance for Breakfast')),
                ('lunch', models.BooleanField(default=False, help_text='Attendance for Lunch')),
                ('dinner', models.BooleanField(default=False, help_text='Attendance for Dinner')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mess_attendances', to='coustom_admin.hostels')),
                ('mess_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='messincharge.messstudent')),
            ],
            options={
                'verbose_name': 'Mess Attendance',
                'verbose_name_plural': 'Mess Attendances',
                'unique_together': {('mess_student', 'date')},
            },
        ),
    ]
